name: UltimateFactions
main: de.miinoo.factions.FactionsSystem
version: 4.1.2
api-version: 1.13
author: Miinoo_
softdepend:
  - PlaceholderAPI
  - dynmap
depend:
  - Vault
commands:
  faction:
    aliases: [f]

